contact_links:
  - name: "❓ Questions about this project"
    url: https://github.com/thibaudcolas/tailwindcss-vanilla-sass/discussions
    about: Use GitHub Discussions to get help with this project.
